version: "3.8"
services:
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: scrumtoolset
    volumes:
      - ./mariadb-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -hlocalhost -uroot -pexample"
      interval: 3s
      timeout: 50s
      retries: 15
volumes:
  mariadb-data: