version: "1"
services:
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client/src:/src
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/src